[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
# Formatter configuration
[fmt]
line_length = 100

evm_version = "prague"


